export const algerianWilayas = [
  { code: '01', name: 'Adrar', zone: 4, delivery_price: 1050, stopdesk_price: 850, delay_days: 3 },
  { code: '02', name: 'Chlef', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '03', name: 'Laghouat', zone: 3, delivery_price: 950, stopdesk_price: 750, delay_days: 1 },
  { code: '04', name: 'Oum El Bouaghi', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '05', name: 'Batna', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '06', name: 'Bejaia', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '07', name: 'Biskra', zone: 3, delivery_price: 950, stopdesk_price: 750, delay_days: 1 },
  { code: '08', name: 'Bechar', zone: 4, delivery_price: 1050, stopdesk_price: 850, delay_days: 3 },
  { code: '09', name: 'Blida', zone: 1, delivery_price: 700, stopdesk_price: 550, delay_days: 1 },
  { code: '10', name: 'Bouira', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '11', name: 'Tamanrasset', zone: 5, delivery_price: 1600, stopdesk_price: 1400, delay_days: 6 },
  { code: '12', name: 'Tebessa', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '13', name: 'Tlemcen', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '14', name: 'Tiaret', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '15', name: 'Tizi Ouzou', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '16', name: 'Alger', zone: 0, delivery_price: 590, stopdesk_price: 450, delay_days: 1 },
  { code: '17', name: 'Djelfa', zone: 3, delivery_price: 950, stopdesk_price: 750, delay_days: 2 },
  { code: '18', name: 'Jijel', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '19', name: 'Setif', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '20', name: 'Saida', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '21', name: 'Skikda', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '22', name: 'Sidi Bel Abbes', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '23', name: 'Annaba', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '24', name: 'Guelma', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '25', name: 'Constantine', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '26', name: 'Medea', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '27', name: 'Mostaganem', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '28', name: "M'Sila", zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '29', name: 'Mascara', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '30', name: 'Ouargla', zone: 3, delivery_price: 950, stopdesk_price: 750, delay_days: 2 },
  { code: '31', name: 'Oran', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '32', name: 'El Bayadh', zone: 4, delivery_price: 1050, stopdesk_price: 850, delay_days: 3 },
  { code: '33', name: 'Illizi', zone: 5, delivery_price: 1600, stopdesk_price: 1400, delay_days: 5 },
  { code: '34', name: 'Bordj Bou Arreridj', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '35', name: 'Boumerdes', zone: 1, delivery_price: 700, stopdesk_price: 550, delay_days: 1 },
  { code: '36', name: 'El Tarf', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '37', name: 'Tindouf', zone: 5, delivery_price: 1600, stopdesk_price: 1400, delay_days: 6 },
  { code: '38', name: 'Tissemsilt', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '39', name: 'El Oued', zone: 3, delivery_price: 950, stopdesk_price: 750, delay_days: 1 },
  { code: '40', name: 'Khenchela', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '41', name: 'Souk Ahras', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '42', name: 'Tipaza', zone: 1, delivery_price: 700, stopdesk_price: 550, delay_days: 1 },
  { code: '43', name: 'Mila', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '44', name: 'Ain Defla', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '45', name: 'Naama', zone: 4, delivery_price: 1050, stopdesk_price: 850, delay_days: 3 },
  { code: '46', name: 'Ain Temouchent', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '47', name: 'Ghardaia', zone: 3, delivery_price: 950, stopdesk_price: 750, delay_days: 2 },
  { code: '48', name: 'Relizane', zone: 3, delivery_price: 950, stopdesk_price: 750, delay_days: 1 },
  { code: '49', name: 'Timimoun', zone: 4, delivery_price: 1050, stopdesk_price: 850, delay_days: 3 },
  { code: '50', name: 'Bordj Badji Mokhtar', zone: 4, delivery_price: 1050, stopdesk_price: 850, delay_days: 3 },
  { code: '51', name: 'Ouled Djellal', zone: 2, delivery_price: 900, stopdesk_price: 650, delay_days: 1 },
  { code: '52', name: 'Beni Abbes', zone: 4, delivery_price: 1050, stopdesk_price: 850, delay_days: 3 },
  { code: '53', name: 'In Salah', zone: 5, delivery_price: 1600, stopdesk_price: 1400, delay_days: 5 },
  { code: '54', name: 'In Guezzam', zone: 5, delivery_price: 1600, stopdesk_price: 1400, delay_days: 5 },
  { code: '55', name: 'Touggourt', zone: 3, delivery_price: 950, stopdesk_price: 750, delay_days: 2 },
  { code: '56', name: 'Djanet', zone: 5, delivery_price: 1600, stopdesk_price: 1400, delay_days: 6 },
  { code: '57', name: "El Mghair", zone: 3, delivery_price: 950, stopdesk_price: 750, delay_days: 1 },
  { code: '58', name: 'El Meniaa', zone: 3, delivery_price: 950, stopdesk_price: 750, delay_days: 2 },
];

export const algerianCommunes = [
  { name: 'Adrar', wilayaCode: '01' },
  { name: 'Tamest', wilayaCode: '01' },
  { name: 'Charouine', wilayaCode: '01' },
  { name: 'Reggane', wilayaCode: '01' },
  { name: 'Inzeghmir', wilayaCode: '01' },
  { name: 'Tit', wilayaCode: '01' },
  { name: 'Ksar Kaddour', wilayaCode: '01' },
  { name: 'Ouled Ahmed Timmi', wilayaCode: '01' },
  { name: 'Chlef', wilayaCode: '02' },
  { name: 'Ténès', wilayaCode: '02' },
  { name: 'Benairia', wilayaCode: '02' },
  { name: 'El Karimia', wilayaCode: '02' },
  { name: 'Tadjena', wilayaCode: '02' },
  { name: 'Taougrit', wilayaCode: '02' },
  { name: 'Boukadir', wilayaCode: '02' },
  { name: 'Ouled Fares', wilayaCode: '02' },
  { name: 'Laghouat', wilayaCode: '03' },
  { name: 'Ksar El Hirane', wilayaCode: '03' },
  { name: 'Bennhar', wilayaCode: '03' },
  { name: 'Sidi Makhlouf', wilayaCode: '03' },
  { name: 'Hassi Delaa', wilayaCode: '03' },
  { name: 'Aflou', wilayaCode: '03' },
  { name: 'Aïn Madhi', wilayaCode: '03' },
  { name: 'Tadjemout', wilayaCode: '03' },
  { name: 'Oum El Bouaghi', wilayaCode: '04' },
  { name: 'Aïn Beïda', wilayaCode: '04' },
  { name: 'Aïn Kercha', wilayaCode: '04' },
  { name: "Aïn M'lila", wilayaCode: '04' },
  { name: 'Behir Chergui', wilayaCode: '04' },
  { name: 'El Amiria', wilayaCode: '04' },
  { name: 'Meskiana', wilayaCode: '04' },
  { name: 'Aïn Fakroun', wilayaCode: '04' },
  { name: 'Batna', wilayaCode: '05' },
  { name: 'Barika', wilayaCode: '05' },
  { name: 'Menaâ', wilayaCode: '05' },
  { name: 'Arris', wilayaCode: '05' },
  { name: "T'kout", wilayaCode: '05' },
  { name: "N'Gaous", wilayaCode: '05' },
  { name: 'Merouana', wilayaCode: '05' },
  { name: 'Aïn Touta', wilayaCode: '05' },
  { name: 'Béjaïa', wilayaCode: '06' },
  { name: 'Amizour', wilayaCode: '06' },
  { name: 'Ferraoun', wilayaCode: '06' },
  { name: 'Taourirt Ighil', wilayaCode: '06' },
  { name: 'Chelata', wilayaCode: '06' },
  { name: 'Seddouk', wilayaCode: '06' },
  { name: 'Akbou', wilayaCode: '06' },
  { name: 'Sidi Aïch', wilayaCode: '06' },
  { name: 'Biskra', wilayaCode: '07' },
  { name: 'Ourlal', wilayaCode: '07' },
  { name: 'Sidi Okba', wilayaCode: '07' },
  { name: 'Sidi Khaled', wilayaCode: '07' },
  { name: 'Zeribet El Oued', wilayaCode: '07' },
  { name: 'Ouled Djellal', wilayaCode: '07' },
  { name: 'Tolga', wilayaCode: '07' },
  { name: 'Foughala', wilayaCode: '07' },
  { name: 'Béchar', wilayaCode: '08' },
  { name: 'El Kheneg', wilayaCode: '08' },
  { name: 'Taghit', wilayaCode: '08' },
  { name: 'Abadla', wilayaCode: '08' },
  { name: 'Béni Ounif', wilayaCode: '08' },
  { name: 'Tabelbala', wilayaCode: '08' },
  { name: 'Igli', wilayaCode: '08' },
  { name: 'Kenadsa', wilayaCode: '08' },
  { name: 'Blida', wilayaCode: '09' },
  { name: 'Chréa', wilayaCode: '09' },
  { name: 'Bouinan', wilayaCode: '09' },
  { name: 'El Affroun', wilayaCode: '09' },
  { name: 'Souma', wilayaCode: '09' },
  { name: 'Meftah', wilayaCode: '09' },
  { name: 'Boufarik', wilayaCode: '09' },
  { name: 'Ouled Yaïch', wilayaCode: '09' },
  { name: 'Bouira', wilayaCode: '10' },
  { name: 'Sour El Ghouzlane', wilayaCode: '10' },
  { name: 'Lakhdaria', wilayaCode: '10' },
  { name: "M'Chedallah", wilayaCode: '10' },
  { name: 'Aïn Bessem', wilayaCode: '10' },
  { name: 'Bordj Okhriss', wilayaCode: '10' },
  { name: 'Kadiria', wilayaCode: '10' },
  { name: 'Bechloul', wilayaCode: '10' },
  { name: 'Tamanrasset', wilayaCode: '11' },
  { name: 'In Guezzam', wilayaCode: '11' },
  { name: 'In Amguel', wilayaCode: '11' },
  { name: 'In Salah', wilayaCode: '11' },
  { name: 'Tazrouk', wilayaCode: '11' },
  { name: 'Aïn Ghar', wilayaCode: '11' },
  { name: 'Idlès', wilayaCode: '11' },
  { name: 'Foggaret Ezzaouia', wilayaCode: '11' },
  { name: 'Tébessa', wilayaCode: '12' },
  { name: 'Bir El Ater', wilayaCode: '12' },
  { name: 'Cheria', wilayaCode: '12' },
  { name: 'El Aouinet', wilayaCode: '12' },
  { name: 'El Ma Labiod', wilayaCode: '12' },
  { name: 'El Ouenza', wilayaCode: '12' },
  { name: 'Hammamet', wilayaCode: '12' },
  { name: 'Negrine', wilayaCode: '12' },
  { name: 'Tlemcen', wilayaCode: '13' },
  { name: 'Maghnia', wilayaCode: '13' },
  { name: 'Nedroma', wilayaCode: '13' },
  { name: 'Remchi', wilayaCode: '13' },
  { name: 'Ghazaouet', wilayaCode: '13' },
  { name: 'Sabra', wilayaCode: '13' },
  { name: "Marsa Ben M'Hidi", wilayaCode: '13' },
  { name: 'Sebdou', wilayaCode: '13' },
  { name: 'Tiaret', wilayaCode: '14' },
  { name: 'Medroussa', wilayaCode: '14' },
  { name: 'Aïn Deheb', wilayaCode: '14' },
  { name: 'Sougueur', wilayaCode: '14' },
  { name: 'Frenda', wilayaCode: '14' },
  { name: 'Ksar Chellala', wilayaCode: '14' },
  { name: 'Rahouia', wilayaCode: '14' },
  { name: 'Mechraa Safa', wilayaCode: '14' },
  { name: 'Tizi Ouzou', wilayaCode: '15' },
  { name: 'Aïn El Hammam', wilayaCode: '15' },
  { name: 'Akbil', wilayaCode: '15' },
  { name: 'Larbaâ Nath Irathen', wilayaCode: '15' },
  { name: 'Tigzirt', wilayaCode: '15' },
  { name: 'Beni Douala', wilayaCode: '15' },
  { name: 'Draa El Mizan', wilayaCode: '15' },
  { name: 'Azeffoun', wilayaCode: '15' },
  { name: 'Bab Ezzouar', wilayaCode: '16' },
  { name: 'El Harrach', wilayaCode: '16' },
  { name: 'Baraki', wilayaCode: '16' },
  { name: 'Dar El Beïda', wilayaCode: '16' },
  { name: 'Bir Mourad Raïs', wilayaCode: '16' },
  { name: 'Bab El Oued', wilayaCode: '16' },
  { name: 'Hussein Dey', wilayaCode: '16' },
  { name: 'Kouba', wilayaCode: '16' },
  { name: 'Bir Khadem', wilayaCode: '16' },
  { name: 'El Biar', wilayaCode: '16' },
  { name: 'Rouiba', wilayaCode: '16' },
  { name: 'Reghaïa', wilayaCode: '16' },
  { name: 'Douira', wilayaCode: '16' },
  { name: 'Chéraga', wilayaCode: '16' },
  { name: 'Draria', wilayaCode: '16' },
  { name: 'Djelfa', wilayaCode: '17' },
  { name: 'Hassi Bahbah', wilayaCode: '17' },
  { name: 'Aïn El Ibel', wilayaCode: '17' },
  { name: 'Messaad', wilayaCode: '17' },
  { name: 'Sidi Ladjel', wilayaCode: '17' },
  { name: 'Faidh El Botma', wilayaCode: '17' },
  { name: 'Dar Chioukh', wilayaCode: '17' },
  { name: 'Aïn Maabed', wilayaCode: '17' },
  { name: 'Jijel', wilayaCode: '18' },
  { name: 'Taher', wilayaCode: '18' },
  { name: 'El Aouana', wilayaCode: '18' },
  { name: 'El Milia', wilayaCode: '18' },
  { name: 'Emir Abdelkader', wilayaCode: '18' },
  { name: 'Chekfa', wilayaCode: '18' },
  { name: 'Djimla', wilayaCode: '18' },
  { name: 'Sidi Maarouf', wilayaCode: '18' },
  { name: 'Sétif', wilayaCode: '19' },
  { name: 'Aïn Kebira', wilayaCode: '19' },
  { name: 'Beni Aziz', wilayaCode: '19' },
  { name: 'El Eulma', wilayaCode: '19' },
  { name: 'Djemila', wilayaCode: '19' },
  { name: 'Boukaâ', wilayaCode: '19' },
  { name: 'Beni Ourtilane', wilayaCode: '19' },
  { name: 'Aïn Oulmene', wilayaCode: '19' },
  { name: 'Saïda', wilayaCode: '20' },
  { name: 'Youb', wilayaCode: '20' },
  { name: 'Hassasna', wilayaCode: '20' },
  { name: 'Sidi Boubekeur', wilayaCode: '20' },
  { name: 'Aïn El Hadjar', wilayaCode: '20' },
  { name: 'Ouled Khaled', wilayaCode: '20' },
  { name: 'Doui Thabet', wilayaCode: '20' },
  { name: 'Tircine', wilayaCode: '20' },
  { name: 'Skikda', wilayaCode: '21' },
  { name: 'Azzaba', wilayaCode: '21' },
  { name: 'El Harrouch', wilayaCode: '21' },
  { name: 'Tamalous', wilayaCode: '21' },
  { name: 'Collo', wilayaCode: '21' },
  { name: 'El Hadaiek', wilayaCode: '21' },
  { name: 'Zitouna', wilayaCode: '21' },
  { name: 'Beni Zid', wilayaCode: '21' },
  { name: 'Sidi Bel Abbès', wilayaCode: '22' },
  { name: 'Tessala', wilayaCode: '22' },
  { name: 'Sfisef', wilayaCode: '22' },
  { name: 'Sidi Ali Benyoub', wilayaCode: '22' },
  { name: 'Ben Badis', wilayaCode: '22' },
  { name: 'Telagh', wilayaCode: '22' },
  { name: 'Merine', wilayaCode: '22' },
  { name: 'Ras El Ma', wilayaCode: '22' },
  { name: 'Annaba', wilayaCode: '23' },
  { name: 'El Bouni', wilayaCode: '23' },
  { name: 'El Hadjar', wilayaCode: '23' },
  { name: 'Berrahal', wilayaCode: '23' },
  { name: 'Seraïdi', wilayaCode: '23' },
  { name: 'Aïn El Bey', wilayaCode: '23' },
  { name: 'Chetaibi', wilayaCode: '23' },
  { name: 'Sidi Amar', wilayaCode: '23' },
  { name: 'Guelma', wilayaCode: '24' },
  { name: 'Aïn Makhlouf', wilayaCode: '24' },
  { name: 'Oued Zenati', wilayaCode: '24' },
  { name: 'Hammam Debagh', wilayaCode: '24' },
  { name: 'Bouchegouf', wilayaCode: '24' },
  { name: 'Heliopolis', wilayaCode: '24' },
  { name: 'Belkheir', wilayaCode: '24' },
  { name: 'Ain Larbi', wilayaCode: '24' },
  { name: 'Constantine', wilayaCode: '25' },
  { name: 'Didouche Mourad', wilayaCode: '25' },
  { name: 'El Khroub', wilayaCode: '25' },
  { name: 'Aïn Smara', wilayaCode: '25' },
  { name: 'Hamma Bouziane', wilayaCode: '25' },
  { name: 'Zighoud Youcef', wilayaCode: '25' },
  { name: 'Ibn Ziad', wilayaCode: '25' },
  { name: 'Aïn Abid', wilayaCode: '25' },
  { name: 'Médéa', wilayaCode: '26' },
  { name: 'Beni Slimane', wilayaCode: '26' },
  { name: 'Berrouaghia', wilayaCode: '26' },
  { name: 'Ksar El Boukhari', wilayaCode: '26' },
  { name: 'Chellalet El Adhaoura', wilayaCode: '26' },
  { name: 'Si Mahdjoub', wilayaCode: '26' },
  { name: 'Aziz', wilayaCode: '26' },
  { name: 'El Azizia', wilayaCode: '26' },
  { name: 'Mostaganem', wilayaCode: '27' },
  { name: 'Aïn Tedles', wilayaCode: '27' },
  { name: 'Hassi Mamèche', wilayaCode: '27' },
  { name: 'Sidi Ali', wilayaCode: '27' },
  { name: 'Mazagran', wilayaCode: '27' },
  { name: 'Stidia', wilayaCode: '27' },
  { name: 'Sour', wilayaCode: '27' },
  { name: 'Achaacha', wilayaCode: '27' },
  { name: "M'Sila", wilayaCode: '28' },
  { name: 'Bou Saada', wilayaCode: '28' },
  { name: 'Sidi Aïssa', wilayaCode: '28' },
  { name: 'Magra', wilayaCode: '28' },
  { name: 'Aïn El Melh', wilayaCode: '28' },
  { name: 'Hammam Dhalaa', wilayaCode: '28' },
  { name: 'Djebel Messaad', wilayaCode: '28' },
  { name: 'Aïn El Khadra', wilayaCode: '28' },
  { name: 'Mascara', wilayaCode: '29' },
  { name: 'Tizi', wilayaCode: '29' },
  { name: 'Sig', wilayaCode: '29' },
  { name: 'Ghriss', wilayaCode: '29' },
  { name: 'Bou Hanifia', wilayaCode: '29' },
  { name: 'Mohammadia', wilayaCode: '29' },
  { name: 'Alaimia', wilayaCode: '29' },
  { name: 'Aïn Fares', wilayaCode: '29' },
  { name: 'Ouargla', wilayaCode: '30' },
  { name: 'Hassi Messaoud', wilayaCode: '30' },
  { name: 'Touggourt', wilayaCode: '30' },
  { name: "N'Goussa", wilayaCode: '30' },
  { name: 'Rouissat', wilayaCode: '30' },
  { name: 'Tamelhat', wilayaCode: '30' },
  { name: 'Sidi Khouiled', wilayaCode: '30' },
  { name: 'El Allia', wilayaCode: '30' },
  { name: 'Oran', wilayaCode: '31' },
  { name: 'Es Senia', wilayaCode: '31' },
  { name: 'Bir El Djir', wilayaCode: '31' },
  { name: 'Arzew', wilayaCode: '31' },
  { name: 'Aïn El Turk', wilayaCode: '31' },
  { name: 'Bethioua', wilayaCode: '31' },
  { name: 'Mers El Kébir', wilayaCode: '31' },
  { name: 'Boutlélis', wilayaCode: '31' },
  { name: 'El Bayadh', wilayaCode: '32' },
  { name: 'Bogtob', wilayaCode: '32' },
  { name: 'El Abiodh Sidi Cheikh', wilayaCode: '32' },
  { name: 'El Ghassoul', wilayaCode: '32' },
  { name: 'Brizina', wilayaCode: '32' },
  { name: 'Chellala', wilayaCode: '32' },
  { name: 'Sidi Tifour', wilayaCode: '32' },
  { name: 'Kraakda', wilayaCode: '32' },
  { name: 'Illizi', wilayaCode: '33' },
  { name: 'Debdeb', wilayaCode: '33' },
  { name: 'Bordj Omar Driss', wilayaCode: '33' },
  { name: 'Djanet', wilayaCode: '33' },
  { name: 'In Amenas', wilayaCode: '33' },
  { name: 'Bordj Bou Arréridj', wilayaCode: '34' },
  { name: 'Ras El Oued', wilayaCode: '34' },
  { name: 'Bordj Ghdir', wilayaCode: '34' },
  { name: 'Mansourah', wilayaCode: '34' },
  { name: 'Medjana', wilayaCode: '34' },
  { name: 'Teniet En Nasr', wilayaCode: '34' },
  { name: 'Bir Kasdali', wilayaCode: '34' },
  { name: 'El Achir', wilayaCode: '34' },
  { name: 'Boumerdès', wilayaCode: '35' },
  { name: 'Dellys', wilayaCode: '35' },
  { name: 'Bordj Menaïel', wilayaCode: '35' },
  { name: 'Boudouaou', wilayaCode: '35' },
  { name: 'Khemis El Khechna', wilayaCode: '35' },
  { name: 'Thenia', wilayaCode: '35' },
  { name: 'Tidjelabine', wilayaCode: '35' },
  { name: 'Kalaâ', wilayaCode: '35' },
  { name: 'El Tarf', wilayaCode: '36' },
  { name: "Ben M'Hidi", wilayaCode: '36' },
  { name: 'Bouteldja', wilayaCode: '36' },
  { name: 'El Kala', wilayaCode: '36' },
  { name: 'Aïn El Assel', wilayaCode: '36' },
  { name: 'Drean', wilayaCode: '36' },
  { name: 'Besbes', wilayaCode: '36' },
  { name: 'Echatt', wilayaCode: '36' },
  { name: 'Tindouf', wilayaCode: '37' },
  { name: 'Oum El Assel', wilayaCode: '37' },
  { name: 'Tissemsilt', wilayaCode: '38' },
  { name: 'Bordj Bou Naama', wilayaCode: '38' },
  { name: 'Theniet El Had', wilayaCode: '38' },
  { name: 'Lazharia', wilayaCode: '38' },
  { name: 'Beni Chaib', wilayaCode: '38' },
  { name: 'Khemisti', wilayaCode: '38' },
  { name: 'Lardjem', wilayaCode: '38' },
  { name: 'Ammari', wilayaCode: '38' },
  { name: 'El Oued', wilayaCode: '39' },
  { name: 'Robbah', wilayaCode: '39' },
  { name: 'Debila', wilayaCode: '39' },
  { name: 'Hassi Khalifa', wilayaCode: '39' },
  { name: 'Taghzout', wilayaCode: '39' },
  { name: 'Reguiba', wilayaCode: '39' },
  { name: 'Magrane', wilayaCode: '39' },
  { name: 'Guemar', wilayaCode: '39' },
  { name: 'Khenchela', wilayaCode: '40' },
  { name: 'Chechar', wilayaCode: '40' },
  { name: 'El Mahmal', wilayaCode: '40' },
  { name: 'Babar', wilayaCode: '40' },
  { name: 'Kaïs', wilayaCode: '40' },
  { name: 'Bouhmama', wilayaCode: '40' },
  { name: 'El Hamma', wilayaCode: '40' },
  { name: 'Yabous', wilayaCode: '40' },
  { name: 'Souk Ahras', wilayaCode: '41' },
  { name: 'Sedrata', wilayaCode: '41' },
  { name: 'Mdaourouch', wilayaCode: '41' },
  { name: 'Taoura', wilayaCode: '41' },
  { name: 'Bir Bouhouche', wilayaCode: '41' },
  { name: 'Ouillen', wilayaCode: '41' },
  { name: 'Mechroha', wilayaCode: '41' },
  { name: 'Henencha', wilayaCode: '41' },
  { name: 'Tipaza', wilayaCode: '42' },
  { name: 'Cherchell', wilayaCode: '42' },
  { name: 'Hadjout', wilayaCode: '42' },
  { name: 'Kolea', wilayaCode: '42' },
  { name: 'Attatba', wilayaCode: '42' },
  { name: 'Bousmail', wilayaCode: '42' },
  { name: 'Douaouda', wilayaCode: '42' },
  { name: 'Fouka', wilayaCode: '42' },
  { name: 'Mila', wilayaCode: '43' },
  { name: 'Ferdjioua', wilayaCode: '43' },
  { name: 'Chelghoum Laïd', wilayaCode: '43' },
  { name: 'Tadjenanet', wilayaCode: '43' },
  { name: 'Rouached', wilayaCode: '43' },
  { name: 'Sidi Merouane', wilayaCode: '43' },
  { name: 'Teleghma', wilayaCode: '43' },
  { name: 'Grarem Gouga', wilayaCode: '43' },
  { name: 'Aïn Defla', wilayaCode: '44' },
  { name: 'Khemis Miliana', wilayaCode: '44' },
  { name: 'Miliana', wilayaCode: '44' },
  { name: 'Rouina', wilayaCode: '44' },
  { name: 'Djendel', wilayaCode: '44' },
  { name: 'El Attaf', wilayaCode: '44' },
  { name: 'Bordj Emir Khaled', wilayaCode: '44' },
  { name: 'Boumedfaa', wilayaCode: '44' },
  { name: 'Naâma', wilayaCode: '45' },
  { name: 'Mecheria', wilayaCode: '45' },
  { name: 'Aïn Sefra', wilayaCode: '45' },
  { name: 'Tiout', wilayaCode: '45' },
  { name: 'Sfissifa', wilayaCode: '45' },
  { name: 'Moghrar', wilayaCode: '45' },
  { name: 'Kasdir', wilayaCode: '45' },
  { name: 'Aïn Ben Khelil', wilayaCode: '45' },
  { name: 'Aïn Témouchent', wilayaCode: '46' },
  { name: 'Hammam Bou Hadjar', wilayaCode: '46' },
  { name: 'Beni Saf', wilayaCode: '46' },
  { name: 'El Malah', wilayaCode: '46' },
  { name: 'Oued Sebbah', wilayaCode: '46' },
  { name: 'El Amria', wilayaCode: '46' },
  { name: 'Sidi Ben Adda', wilayaCode: '46' },
  { name: 'Ouled Boudjemaa', wilayaCode: '46' },
  { name: 'Ghardaïa', wilayaCode: '47' },
  { name: 'El Menia', wilayaCode: '47' },
  { name: 'Dhayet Bendhahoua', wilayaCode: '47' },
  { name: 'Berriane', wilayaCode: '47' },
  { name: 'Metlili', wilayaCode: '47' },
  { name: 'Guerrara', wilayaCode: '47' },
  { name: 'Zelfana', wilayaCode: '47' },
  { name: 'Bounoura', wilayaCode: '47' },
  { name: 'Relizane', wilayaCode: '48' },
  { name: 'Mazouna', wilayaCode: '48' },
  { name: 'Djidiouia', wilayaCode: '48' },
  { name: 'Oued Rhiou', wilayaCode: '48' },
  { name: 'Zemmora', wilayaCode: '48' },
  { name: 'Yellel', wilayaCode: '48' },
  { name: 'Ammi Moussa', wilayaCode: '48' },
  { name: 'Mendes', wilayaCode: '48' },
  { name: 'Timimoun', wilayaCode: '49' },
  { name: 'Ouled Saïd', wilayaCode: '49' },
  { name: 'Tinerkouk', wilayaCode: '49' },
  { name: 'Ksar Kaddour', wilayaCode: '49' },
  { name: 'Bordj Badji Mokhtar', wilayaCode: '50' },
  { name: 'Timiaouine', wilayaCode: '50' },
  { name: 'Ouled Djellal', wilayaCode: '51' },
  { name: 'Ras El Miaad', wilayaCode: '51' },
  { name: 'Doucen', wilayaCode: '51' },
  { name: 'Chaiba', wilayaCode: '51' },
  { name: 'Béni Abbès', wilayaCode: '52' },
  { name: 'Tamtert', wilayaCode: '52' },
  { name: 'Beni Ikhlef', wilayaCode: '52' },
  { name: 'El Ouata', wilayaCode: '52' },
  { name: 'In Salah', wilayaCode: '53' },
  { name: 'Foggaret Ezzaouia', wilayaCode: '53' },
  { name: 'In Ghar', wilayaCode: '53' },
  { name: 'In Guezzam', wilayaCode: '54' },
  { name: 'Tin Zaouatine', wilayaCode: '54' },
  { name: 'Touggourt', wilayaCode: '55' },
  { name: 'Tebesbest', wilayaCode: '55' },
  { name: 'Megarine', wilayaCode: '55' },
  { name: 'Nezla', wilayaCode: '55' },
  { name: 'Zaouia El Abidia', wilayaCode: '55' },
  { name: 'Blidet Amor', wilayaCode: '55' },
  { name: 'Djanet', wilayaCode: '56' },
  { name: 'Bordj El Haouès', wilayaCode: '56' },
  { name: "El M'Ghair", wilayaCode: '57' },
  { name: 'Djamaa', wilayaCode: '57' },
  { name: 'Sidi Amrane', wilayaCode: '57' },
  { name: 'Oum Touyour', wilayaCode: '57' },
  { name: 'El Meniaa', wilayaCode: '58' },
  { name: 'Hassi Gara', wilayaCode: '58' },
  { name: 'Hassi Fehal', wilayaCode: '58' },
];
